AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Advent of code 2020

Globals:
  Function:
    Timeout: 30

Resources:
  Day1Function1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: day1/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /day1/1
            Method: post

  Day1Function2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: day1/
      Handler: app.lambda_handler_2
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /day1/2
            Method: post

  Day2Function1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: day2/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /day2/1
            Method: post

  Day2Function2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: day2/
      Handler: app.lambda_handler_2
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /day2/2
            Method: post

  Day3Function1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: day3/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /day3/1
            Method: post

  Day3Function2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: day3/
      Handler: app.lambda_handler_2
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /day3/2
            Method: post

  Day4Function1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: day4/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /day4/1
            Method: post

  Day4Function2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: day4/
      Handler: app.lambda_handler_2
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /day4/2
            Method: post
  
  Day5Function1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: day5/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /day5/1
            Method: post

  Day5Function2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: day5/
      Handler: app.lambda_handler_2
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /day5/2
            Method: post

  Day6Function1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: day6/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /day6/1
            Method: post

  Day6Function2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: day6/
      Handler: app.lambda_handler_2
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /day6/2
            Method: post

  Day7Function1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: day7/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /day7/1
            Method: post

  Day7Function2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: day7/
      Handler: app.lambda_handler_2
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /day7/2
            Method: post

  Day8Function1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: day8/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /day8/1
            Method: post

  Day8Function2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: day8/
      Handler: app.lambda_handler_2
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /day8/2
            Method: post

  Day9Function1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: day9/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /day9/1
            Method: post

  Day9Function2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: day9/
      Handler: app.lambda_handler_2
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /day9/2
            Method: post
Outputs:
  AdventApi:
    Description: "API Gateway endpoint URL for Advent of Code 2020"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/day1/1"
  