version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "advent"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ipszijmog53m"
s3_prefix = "advent"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
